name: Mirror to Ebrains

on:
  push:
    branches: [ master ]

jobs:
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      - name: sync_master
        uses: wei/git-sync@v3
        with:
          source_repo: "HumanBrainProject/QuickNII"
          source_branch: "master"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB }}@gitlab.ebrains.eu/csucs/quicknii.git"
          destination_branch: "master"
